footprint: [[0.4, 0.3], [0.4, -0.3], [-0.4, -0.3], [-0.4, 0.3]]

#robot_radius: 0.45

# This key parameters greatly determines how much clearance the robot will give to obstacles.
# Set individually in local and global costmaps
footprint_padding: 0.0001

robot_base_frame: segway/base_link

update_frequency: 5.0
transform_tolerance: 1.0

publish_frequency: 1.0
plugins: []

map_type: voxel

static_layer:
  enabled:                  true
  unknown_cost_value:        -1
  lethal_cost_threshold:     100
  map_topic:                 map
  subscribe_to_updates:      true

obstacle_layer:
   conservative_reset_dist: 1.0
   enabled:              true
   unknown_threshold:    15
   mark_threshold:       0
   combination_method:   1
   track_unknown_space:  false    # default: true / false needed to allow global path planning through unknown space
   origin_z: 0.0
   z_resolution: 0.1
   z_voxels: 13                   # Robot is 1.25 meters tall
   publish_voxel_map: true
  
   # NOTE: Tilt head camera downward 0.5 radians to better detect obstacles
   observation_sources: base_scan #rotating_head_scan
  
   base_scan:
      data_type:                LaserScan
      topic:                    segway/base_scan
      marking:                  true
      clearing:                 true
      observation_persistence:  0.0
      expected_update_rate:     1.0
      inf_is_valid:             true
      min_obstacle_height:      0.05
      max_obstacle_height:      0.5
      obstacle_range:           17.0 # Range in specs is 20m
      raytrace_range:           18.0
      
   rotating_head_scan:
      data_type:                LaserScan
      topic:                    /multisense_sl/laser/scan
      marking:                  true
      clearing:                 true
      observation_persistence:  0.0
      expected_update_rate:     1.0
      inf_is_valid:             true
      min_obstacle_height:      0.05
      max_obstacle_height:      2.0
      obstacle_range:           17.0 # Range in specs is 30m
      raytrace_range:           18.0


#voxel_layer:
#   unknown_threshold:    15
#   mark_threshold:       0
#   combination_method:   1
#   track_unknown_space:  true    #true needed for disabling global path planning through unknown space
#   origin_z: 0.0
#   z_resolution: 0.2
#   z_voxels: 20
#   publish_voxel_map: true
#
#   observation_sources: point_cloud_head_camera
#
#   point_cloud_head_camera:
#      data_type:                PointCloud2
#      topic:                    /camera/depth_registered/points
#      marking:                  true
#      clearing:                 true
#      observation_persistence:  0
#      min_obstacle_height:      -0.10
#      max_obstacle_height:      1.3
#      obstacle_range:           2.5
#      raytrace_range:           3.0
         
inflation_layer:
  enabled:              true
  cost_scaling_factor:  2.58  # Old - 10 exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     2.5  # Old - 0.55

