- id: 1
  name: posters
  position: [-18.054, -0.847, 0.000]
  orientation: [0.000, 0.000, 1.000, 0.000]
  ar_tags: [1, 2, 3]
- id: 2
  name: restrooms
  position: [-24.759, -8.266, 0.000]
  orientation: [0.000, 0.000, 1.0009, 0.000]
  ar_tags: [7, 8]
- id: 3
  name: food
  position: [0.538, 0.245, 0.000]
  orientation: [0.000, 0.000, 0.707, 0.707]
  ar_tags: [9, 10]
- id: 4
  name: keynotes
  position: [3.057, -3.598, 0.000]
  orientation: [0, 0, 0, 1]
  ar_tags: [11]
- id: 5
  name: tutorials
  position: [-7.082, 2.493, 0.000]
  orientation: [0.000, 0.000, 0.707, 0.707]
  ar_tags: [12]
- id: 6
  name: demos
  position: [-14.297, -2.631, 0.000]
  orientation: [0.000, 0.000, 1.000, 0.000]
  ar_tags: [13]
- id: 7
  name: exhibits
  position: [13.613, -3.582, 0.000]
  orientation: [0, 0, 0, 1]
  ar_tags: [14]
- id: 8
  name: entrance
  position: [-7.038, -5.763, 0.000]
  orientation: [0.000, 0.000, 0.707, 0.707]
  ar_tags: [15]
