- id: 0
  phrase: How are you today?
  file: how_are_you_today.wav
- id: 1
  phrase: That is a nice shirt you are wearing.
  file: that_is_a_nice_shirt_you_are_wearing.wav
- id: 2
  phrase: Do you have the time please?
  file: do_you_have_the_time_please.wav
- id: 3
  phrase: I will take you to the poster session.
  file: i_will_take_you_to_the_poster_session.wav
- id: 4
  phrase: I will take you to the keynote talks.
  file: i_will_take_you_to_the_keynote_talks.wav
- id: 5
  phrase: Thank you for coming to the conference.
  file:
- id: 6
  phrase: I will take you there now.
  file:
- id: 7
  phrase: Please follow me.
  file:
- id: 8
  phrase: Excuse me.
  file:
- id: 9
  phrase: I need to get by.
  file:
- id: 10
  phrase: Thank you.
  file:
- id: 11
  phrase: My battery is getting low.
  file:
- id: 12
  phrase: I am lost.
  file:
