<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      rmp.urdf.xacro
\authors   Patrick Hussey
\copyright Copyright (c) 2015, Stanley Innovation, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * Neither the name of Stanley Innovation, Inc. nor the names of its contributors may be used to endorse or promote
   products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<robot name="segway_robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Included URDF/XACRO Files -->
    <xacro:include filename="$(find jr_description)/urdf/materials.urdf.xacro" />
    <xacro:include filename="$(find jr_description)/urdf/segway_components/battery.urdf.xacro" />
    <xacro:include filename="$(find jr_description)/urdf/segway_components/i2_wheel.urdf.xacro" />
    <xacro:include filename="$(find jr_description)/urdf/segway_components/caster_assembly.urdf.xacro" />
    <xacro:include filename="$(find jr_description)/urdf/segway_components/std_gearbox_chassis.urdf.xacro" />
    <xacro:include filename="$(find jr_description)/urdf/segway_components/single_spacer.urdf.xacro" />
    <xacro:include filename="$(find jr_description)/urdf/segway_components/ui_box.urdf.xacro" />
    <xacro:include filename="$(find jr_description)/urdf/segway_components/ui_box_spacer_mount.urdf.xacro" />
    <xacro:include filename="$(find jr_description)/urdf/sensors.urdf.xacro" />
    <xacro:include filename="$(find jr_description)/robots/jr.gazebo" />

    <property name="M_PI" value="3.14159"/>

    <!-- Wheel Mounting Positions -->
    <xacro:property name="track" value="0.542391" />
    <xacro:property name="wheel_vertical_offset" value="0.08255015" />

    <!-- Wheel Properties -->
    <xacro:property name="wheel_length" value="0.09224900" />
    <xacro:property name="wheel_radius" value="0.2405681" />

    <!-- Base link is the center of the robot's chassis between the motors projected on the ground -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.05 0.001" />
        </geometry>
        <material name="Red" />
      </visual>
    </link>    
    
    <!-- Sibot Case -->
    <link name="sibot_case_link">
       <inertial>
          <origin xyz="-0.21711 -0.0002007 0.84568" rpy="0 0 0" />
          <mass value="1.752" />
          <inertia ixx="0.0051007" ixy="1.2402E-05" ixz="-0.00021495" 
          iyy="0.0059117" iyz="-6.6044E-06" izz="0.0043871" />
       </inertial>
       <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
             <mesh filename="package://jr_description/meshes/sibot_case.stl" scale="0.9 1 0.9" />
          </geometry>
          <material name="">
             <color rgba="0.6 0.6 0.6 1" />
          </material>
       </visual>
       <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
             <mesh filename="package://jr_description/meshes/sibot_case.stl" scale="0.9 1 0.9" />
          </geometry>
      </collision>
   </link>
   
   <joint name="base_case_joint" type="fixed" >
       <origin xyz="0 0 0.025" rpy="0 0 0" />
	   <parent link="base_link" />
	   <child link="sibot_case_link" />
   </joint>
    
    <!--Chassis -->
    <xacro:std_gearbox_chassis chassis_prefix="base" parent="base_link">
        <origin xyz="0 0 ${-wheel_vertical_offset + wheel_radius}" rpy="0 0 0" />
    </xacro:std_gearbox_chassis>
    
    <link name="inertial_collision_link">
		<inertial>
			<mass value="36.914402" />
			<origin xyz="-0.043407 0.000037 0.060079" />
			<!-- inertia ixx="0.538664"  ixy="0.017957" ixz="-0.077476"
                     iyx="0.017957"  iyy="0.538664" iyz="0.000018"
                     izx="-0.077476" izy="0.000018" izz="1.240229" / -->
                     
			<inertia ixx="0.538664"  ixy="0.017957" ixz="-0.077476"
                     iyx="0.017957"  iyy="200.0" iyz="0.000018"
                     izx="-0.077476" izy="0.000018" izz="1.240229" />
		</inertial>
        <collision>
			<geometry>
				<mesh filename="package://jr_description/meshes/collision/RMP210_chassis_collision.stl" />
			</geometry>
		</collision>
	</link>
	
  <!-- Multisense head unit -->
  <link name="head_root">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>
  
  <joint name="head_root_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="head_root" />
    <child link="head" />
  </joint>

  <joint name="head_root_to_base_link_joint" type="fixed">
    <origin xyz="-0.13775 0 0.77" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="head_root" />
  </joint>

  <!-- These next two are from the sibot.URDF file -->
  <link name="microstrain_imu_frame"/>
  
  <joint name="microstrain_imu_frame_joint" type="fixed">
    <origin xyz="-0.18877 0.0 0.74640" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="microstrain_imu_frame" />
  </joint>
  
  <link name="gps_rcvr_frame"/>
  
  <joint name="microstrain_gps_frame_joint" type="fixed">
    <origin xyz="-0.25728 0.0 0.94843" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="gps_rcvr_frame" />
  </joint>
  
  <!-- These next three are from the ros-indigo-multisense-description/urdf package -->
  <!--
  <link name="accel"/>
  <joint name="accel_joint" type="fixed">
     <origin xyz="-.0475 .0302 -.00275" rpy="0 1.5707 0"/>
     <parent link="head_root"/>
     <child link="accel"/>
  </joint>

  <link name="mag"/>
  <joint name="mag_joint" type="fixed">
     <origin xyz="-.0475 .0302 -.00275" rpy="0 1.5707 0"/>
     <parent link="head_root"/>
     <child link="mag"/>
  </joint>

  <link name="gyro"/>
  <joint name="gyro_joint" type="fixed">
     <origin xyz="-.0476 .0388 -.00075" rpy="1.5707 3.14159 1.5707 "/>
     <parent link="head_root"/>
     <child link="gyro"/>
  </joint>
  -->
  
  <!--
  <link name="gyro" />
  <joint name="gyro_joint" type="fixed">
    <origin xyz="0.065 -0.0137 -0.0075" rpy="-1.5708 0 -1.5708" />
    <parent link="head_root" />
    <child link="gyro" />
  </joint>

  <link name="mag" />
  <joint name="mag_joint" type="fixed">
    <origin xyz="0.065 -0.0223 -0.0095" rpy="0 1.5708 0" />
    <parent link="head_root" />
    <child link="mag" />
  </joint>
  -->
  
  <!-- End Multisense Head Attachment -->
	
  <link name="rear_right_camera_frame">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>
  
  <joint name="rear_right_camera_frame_joint" type="fixed">
    <origin xyz="-0.28657 -0.050243 0.66008" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="rear_right_camera_frame" />
  </joint>

  <link name="rear_right_camera_optical_frame" />
  <joint name="rear_right_camera_optical_frame_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.5708 0 2.1817" />
    <parent link="rear_right_camera_frame" />
    <child link="rear_right_camera_optical_frame" />
  </joint>
  
  <link name="rear_left_camera_frame">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>
  
  <joint name="rear_left_camera_frame_joint" type="fixed">
    <origin xyz="-0.28657 0.050243 0.66008" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="rear_left_camera_frame" />
  </joint>

  <link name="rear_left_camera_optical_frame" />
  <joint name="rear_left_camera_optical_frame_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.5708 0 0.95993" />
    <parent link="rear_left_camera_frame" />
    <child link="rear_left_camera_optical_frame" />
  </joint>
	
  <joint name="inertial_collision_joint" type="fixed" >
     <parent link="base_chassis_link" />
     <child link="inertial_collision_link" />
  </joint>                    

  <!--Gearbox Spacers -->
  <xacro:single_spacer spacer_prefix="left" parent="base_chassis_link">
     <origin xyz="0 0.19582 0.00665015" rpy="0 0 0" />
  </xacro:single_spacer>
  <xacro:single_spacer spacer_prefix="right" parent="base_chassis_link">
     <origin xyz="0 -0.19582 0.00665015" rpy="0 0 ${M_PI}" />
  </xacro:single_spacer>         

  <!-- Propulsion Batteries -->
  <xacro:battery battery_prefix="mcu_1" parent="base_chassis_link">
     <origin xyz="-0.09298 0 0" rpy="0 0 0" />
  </xacro:battery>

  <!-- UI Box -->
  <xacro:ui_box_spacer_mount parent="base_chassis_link">
     <origin xyz="-0.1016 0 0.1273" rpy="0 0 0" />
  </xacro:ui_box_spacer_mount>

  <xacro:ui_box parent="base_chassis_link">
     <origin xyz="-0.1016 0 0.1273" rpy="0 0 0" />
  </xacro:ui_box>

  <!-- UI Batteries -->
  <xacro:battery battery_prefix="aux" parent="base_chassis_link">
     <origin xyz="-0.07845 0 0.1932753" rpy="${M_PI} 0 0" />
  </xacro:battery>

  <!-- Segway wheel macros -->
  <xacro:i2_wheel wheel_prefix="left" parent="base_chassis_link" visual_rotation="0.0">
     <origin xyz="0 ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:i2_wheel>
  <xacro:i2_wheel wheel_prefix="right" parent="base_chassis_link" visual_rotation="${M_PI}">
     <origin xyz="0 ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:i2_wheel>

  <!-- Segway Caster Assembly-->
  <xacro:if value="$(optenv SEGWAY_HAS_REAR_CASTER false)">
     <xacro:caster_assembly caster_prefix="rear" parent="base_chassis_link">
        <origin xyz="-0.31472057 0 0.02425235" rpy="0 0 0" />
     </xacro:caster_assembly>
  </xacro:if>

  <xacro:if value="$(optenv SEGWAY_HAS_FRONT_CASTER false)">
     <xacro:caster_assembly caster_prefix="front" parent="base_chassis_link">
        <origin xyz="0.31472057 0 0.02425235" rpy="0 0 ${M_PI}" />
     </xacro:caster_assembly>
  </xacro:if>

  <!-- Setup the sensors -->
  <xacro:segway_sensors />
      
</robot>
